"use strict";
function Abort(undefined) { }
function AbortIf() { }
function AbortIfConditionIsFalse(undefined) { }
function AbortIfConditionIsTrue(undefined) { }
function AddHealthPoolToPlayer() { }
function AllowButton() { }
function ApplyImpulse() { }
function AttachPlayers() { }
function BigMessage() { }
function Break(undefined) { }
function CallSubroutine() { }
function CancelPrimaryAction() { }
function ChaseGlobalVariableAtRate() { }
function ChaseGlobalVariableOverTime() { }
function ChasePlayerVariableAtRate() { }
function ChasePlayerVariableOverTime() { }
function ClearStatus() { }
function Communicate() { }
function Continue(undefined) { }
function CreateBeamEffect() { }
function CreateDummyBot() { }
function CreateEffect() { }
function CreateHUDText() { }
function CreateIcon() { }
function CreateInWorldText() { }
function CreateProgressBarHUDText() { }
function CreateProgressBarInWorldText() { }
function Damage() { }
function DeclareMatchDraw(undefined) { }
function DeclarePlayerVictory() { }
function DeclareRoundDraw(undefined) { }
function DeclareRoundVictory() { }
function DeclareTeamVictory() { }
function DestroyAllDummyBots(undefined) { }
function DestroyAllEffects(undefined) { }
function DestroyAllHUDText(undefined) { }
function DestroyAllIcons(undefined) { }
function DestroyAllInWorldText(undefined) { }
function DestroyDummyBot() { }
function DestroyEffect() { }
function DestroyHUDText() { }
function DestroyIcon() { }
function DestroyInWorldText() { }
function DestroyProgressBarHUDText() { }
function DestroyProgressBarInWorldText() { }
function DetachPlayers() { }
function DisableBuiltInGameModeAnnouncer(undefined) { }
function DisableBuiltInGameModeCompletion(undefined) { }
function DisableBuiltInGameModeMusic(undefined) { }
function DisableBuiltInGameModeRespawning() { }
function DisableBuiltInGameModeScoring(undefined) { }
function DisableDeathSpectateAllPlayers() { }
function DisableDeathSpectateTargetHUD() { }
function DisableGameModeHUD() { }
function DisableGameModeInWorldUI() { }
function DisableHeroHUD() { }
function DisableInspectorRecording(undefined) { }
function DisableKillFeed() { }
function DisableMessages() { }
function DisableMovementCollisionWithEnvironment() { }
function DisableMovementCollisionWithPlayers() { }
function DisableNameplates() { }
function DisableScoreboard() { }
function DisableTextChat() { }
function DisableVoiceChat() { }
function DisallowButton() { }
function EnableBuiltInGameModeAnnouncer(undefined) { }
function EnableBuiltInGameModeCompletion(undefined) { }
function EnableBuiltInGameModeMusic(undefined) { }
function EnableBuiltInGameModeRespawning() { }
function EnableBuiltInGameModeScoring(undefined) { }
function EnableDeathSpectateAllPlayers() { }
function EnableGameModeHUD() { }
function EnableGameModeInWorldUI() { }
function EnableHeroHUD() { }
function EnableInspectorRecording(undefined) { }
function EnableKillFeed() { }
function EnableMessages() { }
function EnableMovementCollisionWithEnvironment() { }
function EnableMovementCollisionWithPlayers() { }
function EnableNameplates() { }
function EnableScoreboard() { }
function EnableTextChat() { }
function EnableVoiceChat() { }
function End() { }
function ForGlobalVariable() { }
function ForPlayerVariable() { }
function GoToAssembleHeroes() { }
function Heal() { }
function If() { }
function Kill() { }
function LogToInspector() { }
function Loop() { }
function LoopIf() { }
function LoopIfConditionIsFalse() { }
function LoopIfConditionIsTrue() { }
function ModifyGlobalVariable() { }
function ModifyGlobalVariableAtIndex() { }
function ModifyPlayerScore() { }
function ModifyPlayerVariable() { }
function ModifyPlayerVariableAtIndex() { }
function ModifyTeamScore() { }
function MovePlayertoTeam() { }
function PauseMatchTime() { }
function PlayEffect() { }
function PreloadHero() { }
function PressButton() { }
function RemoveAllHealthPoolsFromPlayer() { }
function RemoveHealthPoolFromPlayer() { }
function RemovePlayer() { }
function ResetPlayerHeroAvailability() { }
function Respawn() { }
function RestartMatch() { }
function Resurrect() { }
function ReturntoLobby() { }
function SetAbility1Enabled() { }
function SetAbility2Enabled() { }
function SetAbilityCharge() { }
function SetAbilityCooldown() { }
function SetAbilityResource() { }
function SetAimSpeed() { }
function SetAmmo() { }
function SetCrouchEnabled() { }
function SetDamageDealt() { }
function SetDamageReceived() { }
function SetEnvironmentCreditPlayer() { }
function SetFacing() { }
function SetGlobalVariable() { }
function SetGlobalVariableAtIndex() { }
function SetGravity() { }
function SetHealingDealt() { }
function SetHealingReceived() { }
function SetInvisible() { }
function SetJumpEnabled() { }
function SetJumpVerticalSpeed() { }
function SetKnockbackDealt() { }
function SetKnockbackReceived() { }
function SetMatchTime() { }
function SetMaxAmmo() { }
function SetMaxHealth() { }
function SetMeleeEnabled() { }
function SetMoveSpeed() { }
function SetObjectiveDescription() { }
function SetPlayerAllowedHeroes() { }
function SetPlayerHealth() { }
function SetPlayerScore() { }
function SetPlayerVariable() { }
function SetPlayerVariableAtIndex() { }
function SetPrimaryFireEnabled() { }
function SetProjectileGravity() { }
function SetProjectileSpeed() { }
function SetReloadEnabled() { }
function SetRespawnMaxTime() { }
function SetSecondaryFireEnabled() { }
function SetSlowMotion() { }
function SetStatus() { }
function SetTeamScore() { }
function SetUltimateAbilityEnabled() { }
function SetUltimateCharge() { }
function SetWeapon() { }
function Skip() { }
function SkipIf() { }
function SmallMessage() { }
function StartAccelerating() { }
function StartAssist() { }
function StartCamera() { }
function StartDamageModification() { }
function StartDamageOverTime() { }
function StartFacing() { }
function StartForcingDummyBotName() { }
function StartForcingPlayerOutlines() { }
function StartForcingPlayerPosition() { }
function StartForcingPlayerToBeHero() { }
function StartForcingSpawnRoom() { }
function StartForcingThrottle() { }
function StartGameMode() { }
function StartHealOverTime() { }
function StartHealingModification() { }
function StartHoldingButton() { }
function StartModifyingHeroVoiceLines() { }
function StartRule() { }
function StartScalingBarriers() { }
function StartScalingPlayer() { }
function StartThrottleInDirection() { }
function StartTransformingThrottle() { }
function StopAccelerating() { }
function StopAllAssists() { }
function StopAllDamageModifications() { }
function StopAllDamageOverTime() { }
function StopAllHealOverTime() { }
function StopAllHealingModifications() { }
function StopAssist() { }
function StopCamera() { }
function StopChasingGlobalVariable() { }
function StopChasingPlayerVariable() { }
function StopDamageModification() { }
function StopDamageOverTime() { }
function StopFacing() { }
function StopForcingDummyBotName() { }
function StopForcingPlayerOutlines() { }
function StopForcingPlayerPosition() { }
function StopForcingPlayerToBeHero() { }
function StopForcingSpawnRoom() { }
function StopForcingThrottle() { }
function StopHealOverTime() { }
function StopHealingModification() { }
function StopHoldingButton() { }
function StopModifyingHeroVoiceLines() { }
function StopScalingBarriers() { }
function StopScalingPlayer() { }
function StopThrottleInDirection() { }
function StopTransformingThrottle() { }
function Teleport() { }
function UnpauseMatchTime() { }
function Wait() { }
function WaitUntil() { }
function While() { }
